import { defineConfig } from "eslint/config";
import js from "@eslint/js";
import ts from "typescript-eslint";
import svelte from "eslint-plugin-svelte";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default defineConfig(
  {
    ignores: [
      "node_modules/",
      "**/dist/",
      "**/build/",
      "**/.svelte-kit/",
      "pocketbase/pb_migrations/",
      "pocketbase/pb_hooks/",
      ".superpowers/",
      "**/*.min.js",
    ],
  },
  js.configs.recommended,
  ts.configs.recommended,
  svelte.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      // The repo marks deliberately-unused bindings with a leading underscore
      // (interface conformance, positional params). Honour that convention
      // instead of rewriting every signature.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    files: ["**/*.svelte", "**/*.svelte.ts", "**/*.svelte.js"],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
        extraFileExtensions: [".svelte"],
      },
    },
    rules: {
      // `{"a\nb"}` is not a useless mustache — unquoting it would turn the
      // escape into a literal backslash-n. Only flag genuinely redundant ones.
      "svelte/no-useless-mustaches": ["error", { ignoreStringEscape: true }],
    },
  },
  {
    // Generated by `shadcn-svelte add` and re-generated on upgrade, so it stays
    // byte-for-byte upstream — no inline disable comment here. It re-emits an
    // `href` its caller supplied; resolving is the caller's job, and the rule
    // cannot see that without type-aware linting (a non-goal).
    files: ["apps/web/src/lib/components/ui/button/button.svelte"],
    rules: { "svelte/no-navigation-without-resolve": "off" },
  },
  prettier,
);
